AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - ".git/**/*"
    - ".bundle/**/*"
    - ".vscode/**/*"
    - ".ruby-lsp/**/*"
    - "vendor/**/*"
  SuggestExtensions: false

require:
  - rubocop-minitest
  - rubocop-performance

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/ClassLength:
  Max: 140
  Exclude:
    - "test/*"

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 60

Metrics/AbcSize:
  Max: 40
  Exclude:
    - "test/*"

Metrics/PerceivedComplexity:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 30
